name: PlayerWarpsBlueMap
version: 1.0.0
main: org.bluemaps.playerwarpsbluemap.PlayerWarpsBlueMap
api-version: '26.1.2'

depend:
  - BlueMap
  - PlayerWarps

commands:
  pwbluemap:
    description: PlayerWarps BlueMap bridge commands
    usage: /pwbluemap <reload|sync>
    permission: playerwarpsbluemap.admin

permissions:
  playerwarpsbluemap.admin:
    default: op